name: Run Unit Tests

# Trigger: When do we run?
on: [push, pull_request]

jobs:
  test-code:
    runs-on: ubuntu-latest  # GitHub provides a free VM (Runner)
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3 # Takes your code from the repo to the VM

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Run Tests
      run: go test -v ./...